AUTOMATION_SCHEMA_VERSION = "1.0"

DEFAULT_DOM_TIMEOUT_S = 2.5
DEFAULT_AX_TIMEOUT_S = 2.5
DEFAULT_VISION_TIMEOUT_S = 3.0
DEFAULT_INPUT_TIMEOUT_S = 2.0
DEFAULT_SCRIPT_TIMEOUT_S = 2.0

DEFAULT_MIN_CONFIDENCE_DOM = 0.6
DEFAULT_MIN_CONFIDENCE_AX = 0.55
DEFAULT_MIN_CONFIDENCE_VISION = 0.5
DEFAULT_MIN_CONFIDENCE_INPUT = 0.4

ACTION_CATEGORY_SAFE = frozenset({"click", "scroll", "focus", "wait"})
ACTION_CATEGORY_SENSITIVE = frozenset({"type", "press"})

EXECUTION_MODE_DETERMINISTIC = "deterministic"
EXECUTION_MODE_AI_ASSISTED = "ai-assisted"
